language: python
python:
  - "3.6"

cache:
  pip: true

stages:
  - name: lint
    if: (branch = master) OR (type = pull_request AND head_branch = master)
  - name: test
    if: (branch = master) OR (type = pull_request AND head_branch = master)
  - name: deploy
    if: (tag IS present) OR (branch = master) OR (type = pull_request AND head_branch = master)

jobs:
  include:

    - stage: lint
      script:
        - pip install -U pylint
        - pylint torchrl experiments

    - stage: test
      script:
        - pip install -U .
        - echo "TODO!"

    - stage: deploy
      script:
        - pip install -U -r requirements_dev.txt
        - export PYTHONPATH=$(pwd):$PYTHONPATH
        - pushd docs && make html && popd
        - cp _redirects docs/build/html
      after_success:
        - curl -LO https://github.com/netlify/netlifyctl/releases/download/v0.4.0/netlifyctl-linux-amd64-0.4.0.tar.gz && tar -xzvf netlifyctl-linux-amd64-0.4.0.tar.gz
        # TODO: save all possible releases
        - echo no | ./netlifyctl deploy -n torchrl -A $NETLIFY_ACCESS_TOKEN -P docs/build/html -m "$TRAVIS_COMMIT_MESSAGE" $([[ -z $TRAVIS_PULL_REQUEST_BRANCH && $TRAVIS_BRANCH = "master" ]] && echo "" || echo "-d")
      deploy:
        provider: pypi
        user: $PYPI_USERNAME
        password: $PYPI_PASSWORD
        on:
          tags: true
